site_name: Squad 07 - LicitaX
features:
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search
nav:
      - Sobre: index.md
      - Políticas:
        - Plano de Comunicação: políticas/plano-de-comunicação.md
        - Conduta: políticas/Conduta.md
        - Gerenciamento: políticas/Gerenciamento.md
        - Contribuição: políticas/Contribuição.md
        - Commits: políticas/Commits.md
        - Branches: políticas/Branches.md
        - Issue Template:
          - Bug: políticas/issue-template/Bug.md
          - Custom: políticas/issue-template/Custom.md
          - Feature: políticas/issue-template/Feature.md
          - Pull Request: políticas/issue-template/Pull-Request.md
      - Requisitos:
        - Visão do Produto: requisitos/visaodoproduto.md
        - Requisitos Funcionais: requisitos/requisitosfuncionais.md
        - Requisitos Não-Funcionais: requisitos/requisitosnaofuncionais.md
        - User Story Map: requisitos/userstorymap.md
        - Backlog: requisitos/backlog.md
        - Arquitetura: requisitos/arquitetura.md
        - Prototipo:
          - Prototipo Baixa Fidelidade: requisitos/Prototipo/PrototipoBaixa.md
          - Prototipo Alta Fidelidade: requisitos/Prototipo/PrototipoAlta.md
        - Personas: requisitos/personas.md
        - Story Board: requisitos/storyboard.md
      - Sprints:
        - Sprint 0: 
          - Planejamento: sprints/sprint00/planejamento.md
          - Resultados: sprints/sprint00/resultados.md  
        - Sprint 1:
          - Planejamento: sprints/sprint01/planejamento.md
          - Resultados: sprints/sprint01/resultado.md
        - Sprint 2:
          - Planejamento: sprints/sprint02/planejamento.md
          - Resultados: sprints/sprint02/resultado.md
        - Sprint 3:
          - Planejamento: sprints/sprint03/planejamento.md
          - Resultados: sprints/sprint03/resultado.md
        - Sprint 4:
          - Planejamento: sprints/sprint04/planejamento.md
          - Resultado: sprints/sprint04/resultado.md
        - Sprint 5:
          - Planejamento: sprints/sprint05/planejamento.md
          - Resultado: sprints/sprint05/resultado.md
        - Sprint 6:
          - Planejamento: sprints/sprint06/planejamento.md
          - Resultado: sprints/sprint06/resultado.md
        - Sprint 7:
          - Planejamento: sprints/sprint07/planejamento.md
          - Resultado: sprints/sprint07/resultado.md
theme: material
