site_name: Squad 07 - Ceará
nav:
      - Sobre: index.md
      - Plano de Comunicação: plano-de-comunicação.md
      - Commits: Commits.md
      - Branches: Branches.md
      - Sprints:
        - Sprint 0: 
          - Planejamento: sprints/sprint00/planejamento.md
          - Resultados: sprints/sprint00/resultados.md  
        - Sprint 1:
          - Planejamento: sprints/sprint01/planejamento.md
          - Resultados: sprints/sprint01/resultado.md
        - Sprint 2:
          - Planejamento: sprints/sprint02/planejamento.md
          - Resultados: sprints/sprint02/resultado.md
theme: readthedocs
