site_name: Squad 07 - Ceará
nav:
      - Sobre: index.md
      - Plano de Comunicação: plano-de-comunicação.md
      - Commits: Commits.md
      - Branches: Branches.md
      - Sprints:
        - Sprint 0: 
          - Planejamento: sprints/sprint00/planejamento.md
          - Resultado: sprints/sprint00/resultado.md  
theme: readthedocs
