site_name: Squad 07 - Ceará
nav:
      - Sobre: index.md
      - Plano de Comunicação: plano-de-comunicação.md
      - Commits: Commits.md
      - Branches: Branches.md
      - Sprints: sprints/sprint00/planejamento.md
theme: readthedocs
