name: MkDocs Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
        working-directory: docs

      - name: Build and deploy
        run: |
          mkdocs build --clean
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git clone --branch=gh-pages --single-branch https://github.com/${{ github.repository }} ../gh-pages
          cp -r ../gh-pages/.git ./site/
          cd site
          git add .
          git commit -m "Deployed MkDocs"
          git push origin gh-pages
        working-directory: site
